#include <iostream>
#include <string>

using namespace std;

int resualt = 0;

int request1(int ,int);
int request2(int, int);
int request3(int, int);
int request4(int, int);
int request5(int, int);
void request6(int);
int request7(int, int);
void request0(int, int);
// i1 is first input, and i2 is second input.

int main() {
    //Main function of this app


    // Start Screen
    cout << "Welcome to SFM" << endl;
    cout << "SFM is a open source CLI Calculator for those who want to learn C++" << endl;
    cout << endl << endl;
    int o;
    o = 0;

    // Showing list of operations
    cout << "1 >> Power" << endl;
    cout << "2 >> Multiplication" << endl;
    cout << "3 >> Division" << endl;
    cout << "4 >> Addtion" << endl;
    cout << "5 >> Subtraction" << endl;
    cout << "6 >> Prime Numbers Smaller than x" << endl;
    cout << "7 >> Select a random number smaller than x" << endl;
    cout << "0 >> For a hidden surprise! (Most likely easter egg)" << endl;
    cout << "Select what operation do you want (Default: 0): ";
    cin >> o;
    // Defining TWO Variables

    int x1 , x2;
    x1 = 1;
    x2 = 1;
    // Requesting Values for Variables
    cout << "Enter Number One (Default: 1):" << " ";
    cin >> x1;
    cout << "Enter Number Two (Default: 1):" << " ";
    cin >> x2;
    cout << endl;
    
    // Checking Operation Selected
    if (o == 1) {
        int one = request1(x1 , x2);
        cout << "Your Resualt: " << one << endl;
    } else if (o == 2) {
        int two = request2(x1 , x2);
        cout << "Your Resualt: " << two << endl;
    } else if (o == 3) {
        int three = request3(x1 , x2);
        cout << "Your Resualt: " << three << endl;
    } else if (o == 4) {
        int four = request4(x1 , x2);
        cout << "Your Resualt: " << four << endl;
    } else if (o == 5) {
        int five = request5(x1 , x2);
        cout << "Your Resualt: " << five << endl;
    } else if (o == 6) {
        if (x1 < 3) {
            cout << "In IsPrime tool, Variable x cannot be smaller than 2!";
            
        } else {
        request6(x1);
            }
    } else if (o == 0) {
        request0(x1, x2);
        } else if (o == 7) {
            int seven = request7(x1, x2);
            cout << "Your Resualt: " << seven << endl;
        } else {
            cout << "Entered input is wrong or unknown!";
        }
    return 0;
    // End of Main Function
 }


int request1(int i1, int i2) {
    // This is Function for Power
    int f = 1;
    for (size_t i; i <= i2; i++) {
        f = f * i1;
    }
    return f;
    // Hard, Huh?
}
int request2(int i1, int i2) {
    // This is Function for multipcation.
    resualt = i1 * i2;
    return resualt;
    // So simple, huh?
}
int request3(int i1, int i2) {
    // This is Function for division.
    resualt = i1 / i2;
    return resualt;
    // So Simple? huh x2?
}
int request4(int i1, int i2) {
    // This is Function for Addition.
    resualt = i1 + i2;
    return resualt;
    // So Simple? huh x3?
}
int request5(int i1, int i2) {
    // This is Function for Subtrtaction.
    resualt = i1 - i2;
    return resualt;
    // So Simple? huh x4?
}
void request6(int i1) {
    // This is Function for IsPrime tool.
    cout << "2" << endl;
    bool isPrime;
    for (size_t i = 3; i < i1; i += 2) {
        isPrime = true;
        for (size_t j = 2; j < i; j++) {
            if (i % j == 0) {
                isPrime = false;
                break;
            }
            
            }
            if (isPrime == true) {
            cout << i << endl;
        }
    }
    // Hard, huh x2?
}
int request7(int x, int y) {
    // function for random number!
    size_t z = rand() % x + y;
    return z;
    // Super easy to make!
}
void request0(int x, int y) {
    // Function for hidden feature! >> Huge number generator!

    int i;
    cout << "Select a number: ";
    cin >> i;
    i = i * i * i * i * i;
    size_t x9 = rand() % 9999;
    int lm = x9 * i * x * y * x;
    cout << "This is a semi-random generated number, half of it is generated by AI, and other half is based on your x & y selections: " << lm << endl;
    // return 0;  Just kidding! you cannot have "return" in a void var
    // Kind of hard, I guess?
}

// I'm happy! my first 160 line program is working just fine!